name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out the information below to help us diagnose the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Call tool `wireshark_get_packet_list` with file `...`
        2. Set parameter `...` to `...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include full error messages if applicable.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Wireshark MCP Version
      placeholder: e.g., 0.4.0
    validations:
      required: true

  - type: input
    id: tshark_version
    attributes:
      label: TShark Version
      description: Run `tshark --version` and paste the first line.
      placeholder: e.g., TShark (Wireshark) 4.2.3
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: e.g., 3.11.4
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots that might help.
